import Contact from "@/components/Contact/Contact";
import Features from "@/components/Features/Features";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Services from "@/components/Services/Services";
import Sponsors from "@/components/Sponsors/Sponsors";
import Team from "@/components/Team/Team";

import Head from "next/head";
import styles from "../styles/Header.module.css";
export default function Home() {
  return (
    <>
      <Head>
        <title>Crew Labs App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.heading}>
        <Header />
        <Sponsors />
        <Features />
        <div className="team_services_section">
          <Services />
          <Team />
        </div>
        <Contact />
        <Footer />
      </div>
    </>
  );
}
